language: node_js
node_js:
    - '8'

cache:
    npm: true
    directories:
        - node_modules
        - dist/

env:
    global:
        - GITHUB_ORG="https://GH_TOKEN@github.com"
        - REPO_NAME="ng-rxjs-state-management-demo"
        - GITHUB_NAME="railsstudent"
        - GITHUB_EMAIL="cleung334@gmail.com"

# before_install:
#     - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
#     - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
    - npm install --no-save

script:
    - npm run audit
    - npm run prettier
    - npm run lint
    - npm run test-headless
    - npm run build-ngh

after_success:
    - ngh --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --dir=dist/ng-rxjs-state-management-demo --no-silent

branches:
    only:
        - master
